-- MySQL Script generated by MySQL Workbench
-- 11/19/16 20:45:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `id` INT NOT NULL,
  `Fecha_de_Venta` DATE NULL,
  `Nombre_Cajero` LONGTEXT NULL,
  `Codigo_de_Barras` BIGINT NULL,
  `Cantidad_Articulo` SMALLINT NULL,
  `Vendedor` LONGTEXT NULL,
  `Nombre_del_Cliente` LONGTEXT NULL,
  `Nombre_del_Articulo` LONGTEXT NULL,
  `Valor_Individual_del_Articulos` VARCHAR(45) NULL,
  `Descuentos` VARCHAR(45) NULL,
  `Impuesto IVA` VARCHAR(45) NULL,
  `Subtotal` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursales` (
  `NIT_Sucursal` INT NOT NULL,
  `Nombre_Sucursal` LONGTEXT NULL,
  `Proveedores` MEDIUMTEXT NULL,
  `Precio_Articulo_Proveedores` VARCHAR(45) CHARACTER SET 'utf32' NULL,
  `Inventario` BIGINT NULL,
  `Impuesto_Sucursal` VARCHAR(45) NULL,
  `Servicios_y_Otros` VARCHAR(45) NULL,
  `Perdidas` VARCHAR(45) NULL,
  `Total_Ventas` VARCHAR(45) NULL,
  PRIMARY KEY (`NIT_Sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_cs;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `Numero_de_Cliente` INT NOT NULL,
  `Nombre_del_Cliente` VARCHAR(45) NULL,
  `Cedula_de_Ciudadania` VARCHAR(45) NULL,
  `Puntos_Acumulados` VARCHAR(45) NULL,
  `Descuentos_Realizados` VARCHAR(45) NULL,
  `Articulos_Comprados` VARCHAR(45) NULL,
  `Subtotal_de_Compras` VARCHAR(45) NULL,
  PRIMARY KEY (`Numero_de_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedores` (
  `idVendedores` INT NOT NULL,
  `Nombre` MEDIUMTEXT NULL,
  `Apellidos` LONGTEXT NULL,
  `Ventas_Concretadas` VARCHAR(45) NULL,
  `Comision` VARCHAR(45) NULL,
  `ARP/Riesgos_Profesionales` VARCHAR(45) NULL,
  `EPS/Caja_de_Compensacion` VARCHAR(45) NULL,
  `Festivos_y_Domingos` VARCHAR(45) NULL,
  `Banco/Entidad_Financiera` VARCHAR(45) NULL,
  `N.de Cuenta` VARCHAR(45) NULL,
  `Anticipos` VARCHAR(45) NULL,
  `Descuentos` VARCHAR(45) NULL,
  `Total_Devengado` VARCHAR(45) NULL,
  PRIMARY KEY (`idVendedores`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
